#!/usr/bin/env python3
"""Parse the M&E data exports under ``data/projects/<id>/`` into agent-friendly
artifacts:

  * ``<file-stem>.md`` (one PER FILE, next to the upload) — the FULL data of that
    file rendered as Markdown tables (every row, every sheet). This is the
    complete, readable copy of each upload for the agent to work with.
  * ``_parsed.json`` (one per project) — compact, computed AGGREGATES the
    dashboard widgets bind to (metrics, monthly counts, site breakdown, quality
    issues, record counts). The agent designs the dashboard; the numbers come
    from here (no hallucination, and no need to feed thousands of rows to the LLM).
  * ``data/DATA_OVERVIEW.md`` — an index across all projects + files.

Re-run whenever the data changes:

    backend/.venv/bin/python backend/scripts/parse_data.py

Requires: pandas, openpyxl, lxml (backend/pyproject.toml dev group).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data" / "projects"

MONTHS = {1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun",
          7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"}
SITE_KEYWORDS = ("site", "csb", "district", "commune", "region", "région",
                 "fokontany", "centre", "formation_sanitaire")
MONTH_KEYWORDS = ("mois", "month")


# ── full-data markdown ──────────────────────────────────────────────────────

def esc(v: object) -> str:
    """Cell text for a markdown table — full value, only escape table-breaking chars."""
    if v is None:
        return ""
    s = str(v)
    return s.replace("\r", " ").replace("\n", " ").replace("|", "\\|")


def full_table(df: pd.DataFrame) -> str:
    """Render the ENTIRE dataframe (all rows, all columns) as a markdown table."""
    df = df.where(pd.notna(df), "")
    headers = [esc(c) for c in df.columns]
    lines = ["| " + " | ".join(headers) + " |",
             "| " + " | ".join("---" for _ in headers) + " |"]
    for row in df.itertuples(index=False, name=None):
        lines.append("| " + " | ".join(esc(v) for v in row) + " |")
    return "\n".join(lines)


def file_markdown(file: Path, project: str, frames: list[tuple[str, pd.DataFrame]]) -> str:
    md = [
        f"# {file.name}",
        f"\n_Project `{project}` · {human_size(file)} · full data export · "
        "generated by `backend/scripts/parse_data.py`_\n",
    ]
    if not frames:
        md.append("\n> Could not read this file.\n")
    for sheet, df in frames:
        r, c = df.shape
        md.append(f"\n## Sheet: `{sheet}` — {r} rows × {c} columns\n")
        cols = ", ".join(f"`{col}`" for col in df.columns)
        md.append(f"**Columns ({c}):** {cols}\n")
        if r:
            md.append(full_table(df))
        else:
            md.append("_(empty sheet)_")
    return "\n".join(md) + "\n"


# ── aggregates (the real numbers the widgets bind to) ───────────────────────

def _matches(col: str, keywords: tuple[str, ...]) -> bool:
    lc = str(col).lower()
    return any(k in lc for k in keywords)


def _best_site_breakdown(frames: list[tuple[str, str, pd.DataFrame]]) -> list[dict]:
    best: list[dict] = []
    best_rows = 0
    for _file, _sheet, df in frames:
        for col in df.columns:
            if not _matches(col, SITE_KEYWORDS):
                continue
            s = df[col].dropna().astype(str)
            if 2 <= s.nunique() <= 60 and len(s) > best_rows:
                vc = s.value_counts().head(8)
                best = [{"site": k, "value": int(v)} for k, v in vc.items()]
                best_rows = len(s)
    return best


def _best_monthly(frames: list[tuple[str, str, pd.DataFrame]]) -> list[dict]:
    best: dict[int, int] = {}
    best_rows = 0
    for _file, _sheet, df in frames:
        for col in df.columns:
            if not _matches(col, MONTH_KEYWORDS):
                continue
            s = pd.to_numeric(df[col], errors="coerce").dropna()
            s = s[(s >= 1) & (s <= 12)]
            if len(s) > best_rows:
                best = {int(k): int(v) for k, v in s.astype(int).value_counts().items()}
                best_rows = len(s)
    return [{"month": MONTHS[m], "value": best[m]} for m in range(1, 13) if m in best]


def _metrics(frames, sites, monthly) -> list[dict]:
    files = {f for f, _s, _df in frames}
    total = sum(len(df) for _f, _s, df in frames)
    m = [
        {"label": {"fr": "Fichiers de données", "en": "Data files"}, "value": str(len(files)),
         "helper": {"fr": "exports rattachés", "en": "attached exports"}},
        {"label": {"fr": "Enregistrements", "en": "Records"}, "value": f"{total:,}",
         "helper": {"fr": "lignes au total", "en": "rows in total"}},
    ]
    if sites:
        m.append({"label": {"fr": "Sites", "en": "Sites"}, "value": str(len(sites)),
                  "helper": {"fr": "centres / zones détectés", "en": "facilities / areas detected"}})
    if monthly:
        m.append({"label": {"fr": "Mois couverts", "en": "Months covered"}, "value": str(len(monthly)),
                  "helper": {"fr": "période des données", "en": "data period"}})
    return m


def _quality_issues(frames) -> list[dict]:
    issues = []
    for file, _sheet, df in frames:
        if df.shape[0] == 0:
            continue
        for col in df.columns:
            miss = float(df[col].isna().mean()) * 100
            if miss >= 20:
                issues.append({
                    "column": str(col), "file": file, "missing_pct": round(miss, 1),
                    "severity": "high" if miss >= 50 else "medium",
                    "title": {"fr": f"Champ « {col} » incomplet", "en": f"Field “{col}” incomplete"},
                    "detail": {
                        "fr": f"{round(miss, 1)}% de valeurs manquantes dans {file}.",
                        "en": f"{round(miss, 1)}% missing in {file}.",
                    },
                })
    issues.sort(key=lambda i: i["missing_pct"], reverse=True)
    return issues[:6]


def build_aggregates(name: str, frames: list[tuple[str, str, pd.DataFrame]]) -> dict:
    sites = _best_site_breakdown(frames)
    monthly = _best_monthly(frames)
    return {
        "project_id": name,
        "record_counts": [{"file": f, "sheet": s, "rows": int(len(df))} for f, s, df in frames],
        "metrics": _metrics(frames, sites, monthly),
        "monthly": monthly,
        "sites": sites,
        "quality_issues": _quality_issues(frames),
    }


# ── readers ─────────────────────────────────────────────────────────────────

def read_frames(path: Path) -> list[tuple[str, pd.DataFrame]]:
    suf = path.suffix.lower()
    try:
        if suf == ".xlsx":
            return list(pd.read_excel(path, sheet_name=None, engine="openpyxl").items())
        if suf == ".html":
            return [(f"table_{i + 1}", df) for i, df in enumerate(pd.read_html(str(path)))]
        if suf == ".csv":
            return [("csv", pd.read_csv(path))]
    except Exception as exc:  # noqa: BLE001
        print(f"  ⚠️ {path.name}: {exc}")
    return []


def human_size(p: Path) -> str:
    n = float(p.stat().st_size)
    for unit in ("B", "KB", "MB"):
        if n < 1024:
            return f"{n:.0f} {unit}"
        n /= 1024
    return f"{n:.1f} GB"


def main() -> None:
    if not DATA.exists():
        print(f"no data dir at {DATA}")
        sys.exit(1)

    overview = ["# Data overview\n", "_Auto-generated by `backend/scripts/parse_data.py`._\n"]
    for proj in sorted(d for d in DATA.iterdir() if d.is_dir()):
        # clean up the previous per-project summary if present
        (proj / "_PARSED.md").unlink(missing_ok=True)

        files = sorted(f for f in proj.iterdir() if f.suffix.lower() in (".xlsx", ".html", ".csv"))
        overview.append(f"\n## `{proj.name}` — {len(files)} file(s)")
        all_frames: list[tuple[str, str, pd.DataFrame]] = []

        for f in files:
            frames = read_frames(f)
            md_path = proj / f"{f.stem}.md"
            md_path.write_text(file_markdown(f, proj.name, frames), encoding="utf-8")
            rows = sum(len(df) for _s, df in frames)
            overview.append(f"- `{f.name}` ({human_size(f)}, {rows} rows) → `{md_path.name}`")
            for sheet, df in frames:
                all_frames.append((f.name, sheet, df))
            print(f"wrote {md_path.relative_to(REPO)}  ({rows} rows)")

        aggregates = build_aggregates(proj.name, all_frames)
        (proj / "_parsed.json").write_text(
            json.dumps(aggregates, ensure_ascii=False, indent=2), encoding="utf-8")

    (DATA.parent / "DATA_OVERVIEW.md").write_text("\n".join(overview) + "\n", encoding="utf-8")
    print(f"wrote {(DATA.parent / 'DATA_OVERVIEW.md').relative_to(REPO)}")


if __name__ == "__main__":
    main()
